title: Balls Blog Inc
email: reddevelopercat@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  yeah this is the balls blog yall, i post whatever the flying fuck i want here and its on github
  pages so free fucking hosting as well.. i love posting about random shit, "deep" thoughts and linux and developement stuff.
baseurl: "/ballsblog" # the subpath of your site, e.g. /blog
url: "https://github.com/RedDeveloperCat/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: minima

theme: jekyll-dash
plugins:
  - jekyll-feed
  - jekyll-paginate
  - liquid-md5
  - jekyll/tagging


# required by disqus to display comments
url: "https://github.com/RedDeveloperCat/ballsblog/"

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# jekyll-tagging (optional)
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# for github pages custom domains:
# include: [CNAME]

dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: <your-disqus-shortname>  

  # the animation speed of the post scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  avatar_source: github
  github_username: RedDeveloperCat
  #avatar_source: local
  #avatar_path: /assets/avatar.png

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  # social_links:
  #   - url: https://github.com/RedDeveloperCat
  #     icon: github-square
  #     color: red
  
  # wether the author box should be displayed or not
  show_author: true

